# -*- makefile -*-

dir := test

extra_cflags += -I. $(GL_CFLAGS) $(X11_CFLAGS)

test_programs =

ifeq ($(HAVE_X11),Yes)
test_programs += $(dir)/glx-link-call
test_programs += $(dir)/glx-link-gpa
test_programs += $(dir)/glx-link-gpaa
test_programs += $(dir)/glx-dlopen-dlsym
test_programs += $(dir)/glx-dlopen-gpa
test_programs += $(dir)/glx-dlopen-gpaa
test_programs += $(dir)/egl-opengl-link-call
test_programs += $(dir)/egl-opengl-link-gpa
test_programs += $(dir)/egl-opengl-dlopen-dlsym
test_programs += $(dir)/egl-opengl-dlopen-gpa
test_programs += $(dir)/egl-glesv2-link-call
test_programs += $(dir)/egl-glesv2-link-gpa
test_programs += $(dir)/egl-glesv2-dlopen-dlsym
test_programs += $(dir)/egl-glesv2-dlopen-gpa
endif

glx_link_call_srcs = \
	$(dir)/glx-link-call.c \
	$(dir)/util-x11.c

glx_link_call_modules = $(glx_link_call_srcs:.c=.o)

$(dir)/glx-link-call: $(glx_link_call_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ $(GL_LDFLAGS) $(X11_LDFLAGS) -o $@

glx_link_gpa_srcs = \
	$(dir)/glx-link-gpa.c \
	$(dir)/util-x11.c

glx_link_gpa_modules = $(glx_link_gpa_srcs:.c=.o)

$(dir)/glx-link-gpa: $(glx_link_gpa_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ $(GL_LDFLAGS) $(X11_LDFLAGS) -o $@

glx_link_gpaa_srcs = \
	$(dir)/glx-link-gpaa.c \
	$(dir)/util-x11.c

glx_link_gpaa_modules = $(glx_link_gpaa_srcs:.c=.o)

$(dir)/glx-link-gpaa: $(glx_link_gpaa_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ $(GL_LDFLAGS) $(X11_LDFLAGS) -o $@

glx_dlopen_dlsym_srcs = \
	$(dir)/glx-dlopen-dlsym.c \
	$(dir)/util-x11.c

glx_dlopen_dlsym_modules = $(glx_dlopen_dlsym_srcs:.c=.o)

$(dir)/glx-dlopen-dlsym: $(glx_dlopen_dlsym_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ -ldl $(X11_LDFLAGS) -o $@

glx_dlopen_gpa_srcs = \
	$(dir)/glx-dlopen-gpa.c \
	$(dir)/util-x11.c

glx_dlopen_gpa_modules = $(glx_dlopen_gpa_srcs:.c=.o)

$(dir)/glx-dlopen-gpa: $(glx_dlopen_gpa_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ -ldl $(X11_LDFLAGS) -o $@

glx_dlopen_gpaa_srcs = \
	$(dir)/glx-dlopen-gpaa.c \
	$(dir)/util-x11.c

glx_dlopen_gpaa_modules = $(glx_dlopen_gpaa_srcs:.c=.o)

$(dir)/glx-dlopen-gpaa: $(glx_dlopen_gpaa_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ -ldl $(X11_LDFLAGS) -o $@

egl_opengl_link_call_srcs = \
	$(dir)/egl-opengl-link-call.c \
	$(dir)/util-x11.c

egl_opengl_link_call_modules = $(egl_opengl_link_call_srcs:.c=.o)

$(dir)/egl-opengl-link-call: $(egl_opengl_link_call_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ $(EGL_LDFLAGS) $(GL_LDFLAGS) $(X11_LDFLAGS) -o $@

egl_opengl_link_gpa_srcs = \
	$(dir)/egl-opengl-link-gpa.c \
	$(dir)/util-x11.c

egl_opengl_link_gpa_modules = $(egl_opengl_link_gpa_srcs:.c=.o)

$(dir)/egl-opengl-link-gpa: $(egl_opengl_link_gpa_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ $(EGL_LDFLAGS) $(GL_LDFLAGS) $(X11_LDFLAGS) -o $@

egl_opengl_dlopen_dlsym_srcs = \
	$(dir)/egl-opengl-dlopen-dlsym.c \
	$(dir)/util-x11.c

egl_opengl_dlopen_dlsym_modules = $(egl_opengl_dlopen_dlsym_srcs:.c=.o)

$(dir)/egl-opengl-dlopen-dlsym: $(egl_opengl_dlopen_dlsym_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ -ldl $(X11_LDFLAGS) -o $@

egl_opengl_dlopen_gpa_srcs = \
	$(dir)/egl-opengl-dlopen-gpa.c \
	$(dir)/util-x11.c

egl_opengl_dlopen_gpa_modules = $(egl_opengl_dlopen_gpa_srcs:.c=.o)

$(dir)/egl-opengl-dlopen-gpa: $(egl_opengl_dlopen_gpa_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ -ldl $(X11_LDFLAGS) -o $@

egl_glesv2_link_call_srcs = \
	$(dir)/egl-glesv2-link-call.c \
	$(dir)/util-x11.c

egl_glesv2_link_call_modules = $(egl_glesv2_link_call_srcs:.c=.o)

$(dir)/egl-glesv2-link-call: $(egl_glesv2_link_call_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ $(EGL_LDFLAGS) $(GLESV2_LDFLAGS) $(X11_LDFLAGS) -o $@

egl_glesv2_link_gpa_srcs = \
	$(dir)/egl-glesv2-link-gpa.c \
	$(dir)/util-x11.c

egl_glesv2_link_gpa_modules = $(egl_glesv2_link_gpa_srcs:.c=.o)

$(dir)/egl-glesv2-link-gpa: $(egl_glesv2_link_gpa_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ $(EGL_LDFLAGS) $(GLESV2_LDFLAGS) $(X11_LDFLAGS) -o $@

egl_glesv2_dlopen_dlsym_srcs = \
	$(dir)/egl-glesv2-dlopen-dlsym.c \
	$(dir)/util-x11.c

egl_glesv2_dlopen_dlsym_modules = $(egl_glesv2_dlopen_dlsym_srcs:.c=.o)

$(dir)/egl-glesv2-dlopen-dlsym: $(egl_glesv2_dlopen_dlsym_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ -ldl $(X11_LDFLAGS) -o $@

egl_glesv2_dlopen_gpa_srcs = \
	$(dir)/egl-glesv2-dlopen-gpa.c \
	$(dir)/util-x11.c

egl_glesv2_dlopen_gpa_modules = $(egl_glesv2_dlopen_gpa_srcs:.c=.o)

$(dir)/egl-glesv2-dlopen-gpa: $(egl_glesv2_dlopen_gpa_modules)
	$(call quiet,$(FIPS_LINKER) $(CFLAGS)) $^ -ldl $(X11_LDFLAGS) -o $@

test: all $(test_programs)
	@${dir}/fips-test

check: test

SRCS := $(SRCS) \
	$(glx_link_call_srcs) \
	$(glx_link_gpa_srcs) \
	$(glx_link_gpaa_srcs) \
	$(glx_dlopen_dlsym_srcs) \
	$(glx_dlopen_gpa_srcs) \
	$(egl_opengl_link_call_srcs) \
	$(egl_opengl_link_gpa_srcs) \
	$(egl_opengl_dlopen_dlsym_srcs) \
	$(egl_opengl_dlopen_gpa_srcs) \
	$(egl_glesv2_link_call_srcs) \
	$(egl_glesv2_link_gpa_srcs) \
	$(egl_glesv2_dlopen_dlsym_srcs) \
	$(egl_glesv2_dlopen_gpa_srcs)

CLEAN += $(test_programs) \
	$(glx_link_call_modules) \
	$(glx_link_gpa_modules) \
	$(glx_link_gpaa_modules) \
	$(glx_dlopen_dlsym_modules) \
	$(glx_dlopen_gpa_modules) \
	$(egl_opengl_link_call_modules) \
	$(egl_opengl_link_gpa_modules) \
	$(egl_opengl_dlopen_dlsym_modules) \
	$(egl_opengl_dlopen_dlsym_modules) \
	$(egl_glesv2_link_call_modules) \
	$(egl_glesv2_link_gpa_modules) \
	$(egl_glesv2_dlopen_dlsym_modules) \
	$(egl_glesv2_dlopen_dlsym_modules)
